package io.github.smyrgeorge.freepath.transport.lan

import io.github.smyrgeorge.freepath.contact.ContactCard
import io.github.smyrgeorge.freepath.contact.exchange.ContactExchangeMethod
import io.github.smyrgeorge.freepath.contact.exchange.ContactExchangeSession
import io.github.smyrgeorge.freepath.contact.exchange.LanContactExchange
import io.github.smyrgeorge.freepath.transport.HandshakeHandler
import io.github.smyrgeorge.freepath.transport.model.Frame
import io.github.smyrgeorge.freepath.transport.model.FrameType
import kotlinx.coroutines.withTimeout
import kotlinx.serialization.json.Json
import kotlin.io.encoding.Base64

/**
 * [ContactExchangeSession] implementation for the **requestor side** of a LAN exchange.
 *
 * Sends the local card (with PIN) to the responder over [connection], then waits for
 * the responder's signed card in return.  The connection is closed by [close].
 *
 * @param connection The already-connected [LanConnection] to the responder.
 * @param pin        The 4-digit PIN the user entered (generated by the initiator / responder side).
 */
class LanContactExchangeSession(
    private val connection: LanConnection,
    private val pin: String,
) : ContactExchangeSession {

    override val method: ContactExchangeMethod = ContactExchangeMethod.LAN

    /**
     * Encodes [localCard], wraps it in an EXCHANGE frame carrying [pin], and sends it
     * over the connection.
     *
     * @return The encoded signed-card bytes that were placed in the request payload.
     */
    override suspend fun send(localCard: ContactCard, sigKeyPrivate: ByteArray): ByteArray {
        val encoded = LanContactExchange.encode(localCard, sigKeyPrivate)
        val requestPayload = ExchangeFramePayload.Request(
            pin = pin,
            card = Base64.encode(encoded),
        )
        val requestJson = Json.encodeToString(requestPayload)
        val requestFrame = Frame(
            schema = HandshakeHandler.SCHEMA,
            streamId = "exchange",
            seq = 0L,
            type = FrameType.CONTACT_EXCHANGE,
            payload = Base64.encode(requestJson.encodeToByteArray()),
        )
        connection.sendFrame(requestFrame)
        return encoded
    }

    /**
     * Waits for the responder's EXCHANGE response frame, verifies the PIN was accepted,
     * and decodes the peer's signed contact card.
     *
     * @return [Result.success] with the verified peer [ContactCard], or [Result.failure].
     */
    override suspend fun receive(): Result<ContactCard> = runCatching {
        val responseFrame = withTimeout(LanLinkAdapter.CONTACT_EXCHANGE_TIMEOUT_MS) {
            connection.receiveFrame()
        } ?: error("No response from responder")
        val responseBytes = Base64.decode(responseFrame.payload)
        val response = Json.decodeFromString<ExchangeFramePayload.Response>(responseBytes.decodeToString())
        if (!response.ok) error("Exchange rejected: invalid PIN")
        val peerCardBytes = Base64.decode(response.card ?: error("No card in response"))
        LanContactExchange.decode(peerCardBytes).getOrThrow()
    }

    override suspend fun close() {
        connection.close()
    }
}
