package io.github.smyrgeorge.freepath.contact.exchange

import io.github.smyrgeorge.freepath.contact.ContactCard
import io.github.smyrgeorge.freepath.contact.ContactCardSignedCodec

/**
 * Handles LAN-based contact exchange (bidirectional mode).
 *
 * Encodes a signed contact card into raw JSON bytes of the [io.github.smyrgeorge.freepath.contact.ContactCardSigned]
 * and decodes it back, verifying the schema, Node ID, and signature per spec 3.
 *
 * LAN exchange uses a 6-digit PIN (generated by the initiator, entered by the receiver)
 * as a mutual confirmation step; the PIN is single-use with a 60-second expiry.
 * This codec handles only the card payload encoding/decoding — PIN management is handled
 * at the transport layer.
 */
object LanContactExchange : ContactExchange {

    override val method: ContactExchangeMethod = ContactExchangeMethod.LAN

    /**
     * Encodes a [card] by signing it with [sigKeyPrivate] and returns the raw JSON bytes
     * of the [io.github.smyrgeorge.freepath.contact.ContactCardSigned].
     *
     * @param card The contact card to share.
     * @param sigKeyPrivate The Ed25519 private key for signing.
     * @return Raw UTF-8 JSON bytes of the signed card, ready for transmission over LAN.
     */
    override fun encode(card: ContactCard, sigKeyPrivate: ByteArray): ByteArray {
        val signed = ContactCardSignedCodec.seal(card, sigKeyPrivate)
        return ContactCardSignedCodec.encode(signed)
    }

    /**
     * Decodes and verifies a received signed contact card from raw JSON bytes.
     *
     * Performs the following verification checks per spec 3:
     * 1. Schema check - verifies the card schema is supported.
     * 2. Node ID verification - derives Node ID from sigKey and compares.
     * 3. Signature verification - verifies the card signature.
     *
     * @param data The raw JSON bytes of the signed card received over LAN.
     * @return [Result.success] with the verified card, or [Result.failure] on error.
     */
    override fun decode(data: ByteArray): Result<ContactCard> {
        return runCatching {
            val signed = ContactCardSignedCodec.decode(data)
            ContactCardSignedCodec.open(signed).getOrThrow()
        }
    }
}
