[package]
name = "freepath-relay"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "freepath-relay"
path = "src/main.rs"

[dependencies]
# https://crates.io/crates/log
log = "0.4.29"
# https://crates.io/crates/env_logger
env_logger = "0.11"
# https://crates.io/crates/clap
clap = { version = "4", features = ["derive"] }
# https://crates.io/crates/libp2p
libp2p = { version = "0.56.0", features = [
    "tcp", "noise", "yamux",
    "identify", "ping", "rendezvous", "tokio",
    "quic", "dns"
] }
# https://crates.io/crates/libp2p-dns
libp2p-dns = { version = "0.44.0", features = ["tokio"] }
# https://crates.io/crates/libp2p-swarm
libp2p-swarm = { version = "0.47.1", features = ["macros"] }
# https://crates.io/crates/tokio
tokio = { version = "1.50.0", features = ["full"] }
# https://crates.io/crates/futures
futures = "0.3.32"
